- name: httpd install latest
  yum:
    name: httpd
    state: latest
- name: httpd start
  service:
    name: httpd
    state: started
- name: copy file
  copy:
    src: /index.html
    dest: /var/www/html/index.html
    mode: '777'

